version: "3.7"

services:
  app:
    image: cpcwood/dinorun
    env_file:
      - 'config/env/.env'
    depends_on:
      - postgres
    ports:
      - '5000:5000'

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cpcwood
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - '5432:5432'
    volumes:
      - /var/db/psql/13:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U cpcwood -h 127.0.0.1
      interval: 5s