default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_DEVELOPMENT') { 'dinorun_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_TEST') { 'dinorun_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_PRODUCTION') { 'dinorun_production' } %>